# Generated by Django 4.0.5 on 2023-02-15 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('question_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='login.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('comment_writer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='login.user')),
                ('question', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='postapp.question')),
            ],
        ),
    ]
