# Generated by Django 4.0.5 on 2023-02-18 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_delete_profile'),
        ('postapp', '0002_alter_comment_comment_writer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.user'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='login.user'),
        ),
    ]
