# Generated by Django 4.0.5 on 2023-02-19 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postapp', '0002_alter_comment_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='anonymous',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
