# Generated by Django 4.0.5 on 2023-02-27 06:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postapp', '0003_alter_comment_id_alter_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='open_user',
            field=models.ManyToManyField(related_name='like_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
