# Generated by Django 4.0.5 on 2023-02-19 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0004_alter_comment_comment_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_writer',
            new_name='writer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_writer',
            new_name='writer',
        ),
    ]
