# Generated by Django 4.0.5 on 2023-02-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0005_comment_like_count_comment_like_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
