# Generated by Django 4.0.5 on 2023-03-23 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postapp', '0008_alter_comment_like_user_alter_comment_open_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.TextField()),
                ('used', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.TextField()),
                ('accept', models.BooleanField(default=False)),
                ('ownerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beQuestion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
