# Generated by Django 4.0.5 on 2023-03-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0009_recquestion_bequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='bequestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
