# Generated by Django 4.0.5 on 2023-03-23 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postapp', '0010_bequestion_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('anonymous', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('like_count', models.PositiveIntegerField(default=0, null=True)),
                ('like_user', models.ManyToManyField(related_name='beLike_users', to=settings.AUTH_USER_MODEL)),
                ('open_user', models.ManyToManyField(related_name='beOpen_users', to=settings.AUTH_USER_MODEL)),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beComments', to='postapp.bequestion')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beComments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
