# Generated by Django 4.0.5 on 2023-03-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0013_alter_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
