# Generated by Django 4.0.5 on 2023-03-25 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0014_alter_question_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id',
            new_name='commentId',
        ),
    ]
