# Generated by Django 4.0.5 on 2023-03-26 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0015_rename_id_comment_commentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='becomment',
            old_name='id',
            new_name='beCommentId',
        ),
        migrations.RenameField(
            model_name='bequestion',
            old_name='id',
            new_name='beQuestionId',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='id',
            new_name='questionId',
        ),
    ]
