# Generated by Django 4.0.5 on 2023-04-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0016_rename_id_becomment_becommentid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
