# Generated by Django 4.0.5 on 2023-04-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0018_remove_question_publish_comment_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='open_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
