# Generated by Django 4.0.5 on 2023-04-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0019_comment_open_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
