# Generated by Django 4.0.5 on 2023-04-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0020_alter_comment_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
