# Generated by Django 3.2 on 2023-02-16 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('point', models.PositiveIntegerField(default=500)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile/')),
            ],
        ),
    ]
