# Generated by Django 3.2 on 2023-02-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_user_name'),
        ('login', '0005_remove_user_is_staff'),
    ]

    operations = [
    ]
